swagger: '2.0'
host: api-sandbox.factset.com
schemes:
  - https
paths:
  /cognitive/ner/v2/entities:
    post:
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Response'
        '400':
          description: Bad Request
        '401':
          description: 'Error: Unauthorized'
        '500':
          description: Server-side Error
      description: Extract named entities from document text.
      operationId: post_entities_/entities
      parameters:
        - name: payload
          required: true
          in: body
          schema:
            $ref: '#/definitions/Input'
      tags:
        - entities
info:
  title: FactSet NER
  version: 2.0.0
  description: >-
    Extract named entities and their FactSet entity IDs from given document
    text.
produces:
  - application/json
consumes:
  - application/json
securityDefinitions:
  FactSetApiKey:
    type: basic
  FactSetOAuth2:
    type: oauth2
    flow: application
    tokenUrl: https://auth.factset.com/as/token.oauth2
    scopes: {}
security:
  - FactSetApiKey: []
  - FactSetOAuth2: []
tags:
  - name: entities
    description: Named Entity Recognition
definitions:
  Input:
    required:
      - text
    properties:
      text:
        type: string
        description: >-
          English plain text to extract named entities from.  Maxiumum of 10,000
          characters.
        example: >-
          As demand for the coronavirus vaccine plateaus, Ohio Governor Mike
          DeWine is giving state residents a shot to win $1 million. Starting
          May 26, the state will award $1 million each week to an adult who has
          received at least the first dose of the COVID-19 vaccine, DeWine said.
          There will be five total drawings. This will give anyone who has not
          been vaccinated time to get the first dose of Pfizer or Moderna and be
          well on the way to full immunity, DeWine said Wednesday. West Virginia
          Governor Jim Justice wanted to give every vaccinated resident between
          the ages of 16 and 35 a $100 savings bond. States and localities have
          been given wide discretion by the Treasury Department in spending
          federal aid.
      filterEntities:
        type: boolean
        description: Drop lower probability entities using machine learning filtering rules
        default: true
      enableIdLookup:
        type: boolean
        description: Retrieve FactSet IDs for entities
        default: true
    type: object
  Response:
    properties:
      entities:
        type: array
        items:
          $ref: '#/definitions/Entity'
    type: object
  Entity:
    properties:
      type:
        type: string
        description: Type of the extracted named entity (NE).
        example: NE_GPE
        enum:
          - NE_GPE
          - NE_ORG
          - NE_PERSON
          - NE_NUMBER
          - NE_MONEY
          - NE_DATETIME
          - NE_DRUG
          - NE_HEALTH_INDICATION
      text:
        type: string
        description: Text for the named entity, as found in the source text.
      startChar:
        type: integer
        description: Starting character position of the entity text.
        minimum: 0
      endChar:
        type: integer
        description: Ending character position of the entity text.
        minimum: 0
      lookupText:
        type: string
        description: Name of the FactSet entity linked to the text.
      entityId:
        type: string
        description: FactSet Entity ID for the extracted entity.
      lookupUrl:
        type: string
        description: URL to the extracted entity in FactSet.
      associatedOrgs:
        type: array
        description: Organizations associated with this entity.
        items:
          $ref: '#/definitions/Associated_Organization'
    type: object
  Associated_Organization:
    properties:
      name:
        type: string
        description: Name of the entity
      entityId:
        type: string
        description: FactSet Entity ID for the entity
      lookupUrl:
        type: string
        description: FactSet description of the entity
    type: object
responses:
  ParseError:
    description: When a mask can't be parsed
  MaskError:
    description: When any error occurs on mask
